repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2  # Use the revision or tag you want to point at
    hooks:
      - id: black
        args: ["--check", "src/"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.289  # Use the revision or tag you want to point at
    hooks:
      - id: ruff
